-- Primero asegurar que la columna tiene suficiente capacidad (ejecutar solo si es necesario)
ALTER TABLE PAIS ALTER COLUMN Prefijo_telefonico VARCHAR(15);

-- Insertar países con prefijos optimizados
INSERT INTO PAIS (Nombre_pais, Codigo_iso2, Codigo_iso3, Prefijo_telefonico, Moneda, Estado_registro)
VALUES
('Afganistán', 'AF', 'AFG', '+93', 'AFN', 1),
('Albania', 'AL', 'ALB', '+355', 'ALL', 1),
('Alemania', 'DE', 'DEU', '+49', 'EUR', 1),
('Andorra', 'AD', 'AND', '+376', 'EUR', 1),
('Angola', 'AO', 'AGO', '+244', 'AOA', 1),
('Antigua y Barbuda', 'AG', 'ATG', '+1268', 'XCD', 1),  -- Cambiado de +1-268 a +1268
('Arabia Saudita', 'SA', 'SAU', '+966', 'SAR', 1),
('Argelia', 'DZ', 'DZA', '+213', 'DZD', 1),
('Argentina', 'AR', 'ARG', '+54', 'ARS', 1),
('Armenia', 'AM', 'ARM', '+374', 'AMD', 1),
('Australia', 'AU', 'AUS', '+61', 'AUD', 1),
('Austria', 'AT', 'AUT', '+43', 'EUR', 1),
('Azerbaiyán', 'AZ', 'AZE', '+994', 'AZN', 1),
('Bahamas', 'BS', 'BHS', '+1242', 'BSD', 1),  -- Cambiado de +1-242 a +1242
('Bangladés', 'BD', 'BGD', '+880', 'BDT', 1),
('Barbados', 'BB', 'BRB', '+1246', 'BBD', 1),  -- Cambiado de +1-246 a +1246
('Baréin', 'BH', 'BHR', '+973', 'BHD', 1),
('Bélgica', 'BE', 'BEL', '+32', 'EUR', 1),
('Belice', 'BZ', 'BLZ', '+501', 'BZD', 1),
('Benín', 'BJ', 'BEN', '+229', 'XOF', 1),
('Bielorrusia', 'BY', 'BLR', '+375', 'BYN', 1),
('Bolivia', 'BO', 'BOL', '+591', 'BOB', 1),
('Bosnia y Herzegovina', 'BA', 'BIH', '+387', 'BAM', 1),
('Botsuana', 'BW', 'BWA', '+267', 'BWP', 1),
('Brasil', 'BR', 'BRA', '+55', 'BRL', 1),
('Brunéi', 'BN', 'BRN', '+673', 'BND', 1),
('Bulgaria', 'BG', 'BGR', '+359', 'BGN', 1),
('Burkina Faso', 'BF', 'BFA', '+226', 'XOF', 1),
('Burundi', 'BI', 'BDI', '+257', 'BIF', 1),
('Bután', 'BT', 'BTN', '+975', 'BTN', 1),
('Cabo Verde', 'CV', 'CPV', '+238', 'CVE', 1),
('Camboya', 'KH', 'KHM', '+855', 'KHR', 1),
('Camerún', 'CM', 'CMR', '+237', 'XAF', 1),
('Canadá', 'CA', 'CAN', '+1', 'CAD', 1),
('Catar', 'QA', 'QAT', '+974', 'QAR', 1),
('Chad', 'TD', 'TCD', '+235', 'XAF', 1),
('Chile', 'CL', 'CHL', '+56', 'CLP', 1),
('China', 'CN', 'CHN', '+86', 'CNY', 1),
('Chipre', 'CY', 'CYP', '+357', 'EUR', 1),
('Colombia', 'CO', 'COL', '+57', 'COP', 1),
('Comoras', 'KM', 'COM', '+269', 'KMF', 1),
('Corea del Norte', 'KP', 'PRK', '+850', 'KPW', 1),
('Corea del Sur', 'KR', 'KOR', '+82', 'KRW', 1),
('Costa de Marfil', 'CI', 'CIV', '+225', 'XOF', 1),
('Costa Rica', 'CR', 'CRI', '+506', 'CRC', 1),
('Croacia', 'HR', 'HRV', '+385', 'HRK', 1),
('Cuba', 'CU', 'CUB', '+53', 'CUP', 1),
('Dinamarca', 'DK', 'DNK', '+45', 'DKK', 1),
('Dominica', 'DM', 'DMA', '+1767', 'XCD', 1),  -- Cambiado de +1-767 a +1767
('Ecuador', 'EC', 'ECU', '+593', 'USD', 1),
('Egipto', 'EG', 'EGY', '+20', 'EGP', 1),
('El Salvador', 'SV', 'SLV', '+503', 'USD', 1),
('Emiratos Árabes Unidos', 'AE', 'ARE', '+971', 'AED', 1),
('Eritrea', 'ER', 'ERI', '+291', 'ERN', 1),
('Eslovaquia', 'SK', 'SVK', '+421', 'EUR', 1),
('Eslovenia', 'SI', 'SVN', '+386', 'EUR', 1),
('España', 'ES', 'ESP', '+34', 'EUR', 1),
('Estados Unidos', 'US', 'USA', '+1', 'USD', 1),
('Estonia', 'EE', 'EST', '+372', 'EUR', 1),
('Etiopía', 'ET', 'ETH', '+251', 'ETB', 1),
('Filipinas', 'PH', 'PHL', '+63', 'PHP', 1),
('Finlandia', 'FI', 'FIN', '+358', 'EUR', 1),
('Fiyi', 'FJ', 'FJI', '+679', 'FJD', 1),
('Francia', 'FR', 'FRA', '+33', 'EUR', 1),
('Gabón', 'GA', 'GAB', '+241', 'XAF', 1),
('Gambia', 'GM', 'GMB', '+220', 'GMD', 1),
('Georgia', 'GE', 'GEO', '+995', 'GEL', 1),
('Ghana', 'GH', 'GHA', '+233', 'GHS', 1),
('Granada', 'GD', 'GRD', '+1473', 'XCD', 1),  -- Cambiado de +1-473 a +1473
('Grecia', 'GR', 'GRC', '+30', 'EUR', 1),
('Guatemala', 'GT', 'GTM', '+502', 'GTQ', 1),
('Guinea', 'GN', 'GIN', '+224', 'GNF', 1),
('Guinea Ecuatorial', 'GQ', 'GNQ', '+240', 'XAF', 1),
('Guinea-Bisáu', 'GW', 'GNB', '+245', 'XOF', 1),
('Guyana', 'GY', 'GUY', '+592', 'GYD', 1),
('Haití', 'HT', 'HTI', '+509', 'HTG', 1),
('Honduras', 'HN', 'HND', '+504', 'HNL', 1),
('Hungría', 'HU', 'HUN', '+36', 'HUF', 1),
('India', 'IN', 'IND', '+91', 'INR', 1),
('Indonesia', 'ID', 'IDN', '+62', 'IDR', 1),
('Irak', 'IQ', 'IRQ', '+964', 'IQD', 1),
('Irán', 'IR', 'IRN', '+98', 'IRR', 1),
('Irlanda', 'IE', 'IRL', '+353', 'EUR', 1),
('Islandia', 'IS', 'ISL', '+354', 'ISK', 1),
('Islas Marshall', 'MH', 'MHL', '+692', 'USD', 1),
('Islas Salomón', 'SB', 'SLB', '+677', 'SBD', 1),
('Israel', 'IL', 'ISR', '+972', 'ILS', 1),
('Italia', 'IT', 'ITA', '+39', 'EUR', 1),
('Jamaica', 'JM', 'JAM', '+1876', 'JMD', 1),  -- Cambiado de +1-876 a +1876
('Japón', 'JP', 'JPN', '+81', 'JPY', 1),
('Jordania', 'JO', 'JOR', '+962', 'JOD', 1),
('Kazajistán', 'KZ', 'KAZ', '+7', 'KZT', 1),
('Kenia', 'KE', 'KEN', '+254', 'KES', 1),
('Kirguistán', 'KG', 'KGZ', '+996', 'KGS', 1),
('Kiribati', 'KI', 'KIR', '+686', 'AUD', 1),
('Kuwait', 'KW', 'KWT', '+965', 'KWD', 1),
('Laos', 'LA', 'LAO', '+856', 'LAK', 1),
('Lesoto', 'LS', 'LSO', '+266', 'LSL', 1),
('Letonia', 'LV', 'LVA', '+371', 'EUR', 1),
('Líbano', 'LB', 'LBN', '+961', 'LBP', 1),
('Liberia', 'LR', 'LBR', '+231', 'LRD', 1),
('Libia', 'LY', 'LBY', '+218', 'LYD', 1),
('Liechtenstein', 'LI', 'LIE', '+423', 'CHF', 1),
('Lituania', 'LT', 'LTU', '+370', 'EUR', 1),
('Luxemburgo', 'LU', 'LUX', '+352', 'EUR', 1),
('Macedonia del Norte', 'MK', 'MKD', '+389', 'MKD', 1),
('Madagascar', 'MG', 'MDG', '+261', 'MGA', 1),
('Malasia', 'MY', 'MYS', '+60', 'MYR', 1),
('Malaui', 'MW', 'MWI', '+265', 'MWK', 1),
('Maldivas', 'MV', 'MDV', '+960', 'MVR', 1),
('Malí', 'ML', 'MLI', '+223', 'XOF', 1),
('Malta', 'MT', 'MLT', '+356', 'EUR', 1),
('Marruecos', 'MA', 'MAR', '+212', 'MAD', 1),
('Mauricio', 'MU', 'MUS', '+230', 'MUR', 1),
('Mauritania', 'MR', 'MRT', '+222', 'MRU', 1),
('México', 'MX', 'MEX', '+52', 'MXN', 1),
('Micronesia', 'FM', 'FSM', '+691', 'USD', 1),
('Moldavia', 'MD', 'MDA', '+373', 'MDL', 1),
('Mónaco', 'MC', 'MCO', '+377', 'EUR', 1),
('Mongolia', 'MN', 'MNG', '+976', 'MNT', 1),
('Montenegro', 'ME', 'MNE', '+382', 'EUR', 1),
('Mozambique', 'MZ', 'MOZ', '+258', 'MZN', 1),
('Namibia', 'NA', 'NAM', '+264', 'NAD', 1),
('Nauru', 'NR', 'NRU', '+674', 'AUD', 1),
('Nepal', 'NP', 'NPL', '+977', 'NPR', 1),
('Nicaragua', 'NI', 'NIC', '+505', 'NIO', 1),
('Níger', 'NE', 'NER', '+227', 'XOF', 1),
('Nigeria', 'NG', 'NGA', '+234', 'NGN', 1),
('Noruega', 'NO', 'NOR', '+47', 'NOK', 1),
('Nueva Zelanda', 'NZ', 'NZL', '+64', 'NZD', 1),
('Omán', 'OM', 'OMN', '+968', 'OMR', 1),
('Países Bajos', 'NL', 'NLD', '+31', 'EUR', 1),
('Pakistán', 'PK', 'PAK', '+92', 'PKR', 1),
('Palaos', 'PW', 'PLW', '+680', 'USD', 1),
('Panamá', 'PA', 'PAN', '+507', 'USD', 1),
('Papúa Nueva Guinea', 'PG', 'PNG', '+675', 'PGK', 1),
('Paraguay', 'PY', 'PRY', '+595', 'PYG', 1),
('Perú', 'PE', 'PER', '+51', 'PEN', 1),
('Polonia', 'PL', 'POL', '+48', 'PLN', 1),
('Portugal', 'PT', 'PRT', '+351', 'EUR', 1),
('Reino Unido', 'GB', 'GBR', '+44', 'GBP', 1),
('República Centroafricana', 'CF', 'CAF', '+236', 'XAF', 1),
('República Checa', 'CZ', 'CZE', '+420', 'CZK', 1),
('República Democrática del Congo', 'CD', 'COD', '+243', 'CDF', 1),
('República Dominicana', 'DO', 'DOM', '+1809', 'DOP', 1),  -- Usando solo el prefijo principal
('Ruanda', 'RW', 'RWA', '+250', 'RWF', 1),
('Rumanía', 'RO', 'ROU', '+40', 'RON', 1),
('Rusia', 'RU', 'RUS', '+7', 'RUB', 1),
('Samoa', 'WS', 'WSM', '+685', 'WST', 1),
('San Cristóbal y Nieves', 'KN', 'KNA', '+1869', 'XCD', 1),  -- Cambiado de +1-869 a +1869
('San Marino', 'SM', 'SMR', '+378', 'EUR', 1),
('San Vicente y las Granadinas', 'VC', 'VCT', '+1784', 'XCD', 1),  -- Cambiado de +1-784 a +1784
('Santa Lucía', 'LC', 'LCA', '+1758', 'XCD', 1),  -- Cambiado de +1-758 a +1758
('Santo Tomé y Príncipe', 'ST', 'STP', '+239', 'STN', 1),
('Senegal', 'SN', 'SEN', '+221', 'XOF', 1),
('Serbia', 'RS', 'SRB', '+381', 'RSD', 1),
('Seychelles', 'SC', 'SYC', '+248', 'SCR', 1),
('Sierra Leona', 'SL', 'SLE', '+232', 'SLL', 1),
('Singapur', 'SG', 'SGP', '+65', 'SGD', 1),
('Siria', 'SY', 'SYR', '+963', 'SYP', 1),
('Somalia', 'SO', 'SOM', '+252', 'SOS', 1),
('Sri Lanka', 'LK', 'LKA', '+94', 'LKR', 1),
('Suazilandia', 'SZ', 'SWZ', '+268', 'SZL', 1),
('Sudáfrica', 'ZA', 'ZAF', '+27', 'ZAR', 1),
('Sudán', 'SD', 'SDN', '+249', 'SDG', 1),
('Sudán del Sur', 'SS', 'SSD', '+211', 'SSP', 1),
('Suecia', 'SE', 'SWE', '+46', 'SEK', 1),
('Suiza', 'CH', 'CHE', '+41', 'CHF', 1),
('Surinam', 'SR', 'SUR', '+597', 'SRD', 1),
('Tailandia', 'TH', 'THA', '+66', 'THB', 1),
('Tanzania', 'TZ', 'TZA', '+255', 'TZS', 1),
('Tayikistán', 'TJ', 'TJK', '+992', 'TJS', 1),
('Timor Oriental', 'TL', 'TLS', '+670', 'USD', 1),
('Togo', 'TG', 'TGO', '+228', 'XOF', 1),
('Tonga', 'TO', 'TON', '+676', 'TOP', 1),
('Trinidad y Tobago', 'TT', 'TTO', '+1868', 'TTD', 1),  -- Cambiado de +1-868 a +1868
('Túnez', 'TN', 'TUN', '+216', 'TND', 1),
('Turkmenistán', 'TM', 'TKM', '+993', 'TMT', 1),
('Turquía', 'TR', 'TUR', '+90', 'TRY', 1),
('Tuvalu', 'TV', 'TUV', '+688', 'AUD', 1),
('Ucrania', 'UA', 'UKR', '+380', 'UAH', 1),
('Uganda', 'UG', 'UGA', '+256', 'UGX', 1),
('Uruguay', 'UY', 'URY', '+598', 'UYU', 1),
('Uzbekistán', 'UZ', 'UZB', '+998', 'UZS', 1),
('Vanuatu', 'VU', 'VUT', '+678', 'VUV', 1),
('Vaticano', 'VA', 'VAT', '+379', 'EUR', 1),
('Venezuela', 'VE', 'VEN', '+58', 'VES', 1),
('Vietnam', 'VN', 'VNM', '+84', 'VND', 1),
('Yemen', 'YE', 'YEM', '+967', 'YER', 1),
('Yibuti', 'DJ', 'DJI', '+253', 'DJF', 1),
('Zambia', 'ZM', 'ZMB', '+260', 'ZMW', 1),
('Zimbabue', 'ZW', 'ZWE', '+263', 'ZWL', 1);

SELECT * FROM PAIS;
